//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem_Stone_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class insertAgent
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userName { get; set; }
        public string locationName { get; set; }
        public string emailId { get; set; }
        public string contact { get; set; }
    }
}
