//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem_Stone_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemDetail
    {
        public int id { get; set; }
        public string userNames { get; set; }
        public string preSemi { get; set; }
        public string pType { get; set; }
        public string sName { get; set; }
        public string stoneSize { get; set; }
        public string sWeight { get; set; }
        public string sPieces { get; set; }
        public string sDimensions { get; set; }
        public string sColor { get; set; }
        public string stoneShape { get; set; }
        public string sOrigin { get; set; }
        public string sRemark { get; set; }
        public string scerAgency { get; set; }
        public string sCarat { get; set; }
        public string stockId { get; set; }
        public string sSupplierRef { get; set; }
        public string sPurchase { get; set; }
        public string imageName { get; set; }
    }
}
